name       : perl-http-date
version    : '6.05'
release    : 9
source     :
    - https://cpan.metacpan.org/authors/id/O/OA/OALDERS/HTTP-Date-6.05.tar.gz : 365d6294dfbd37ebc51def8b65b81eb79b3934ecbc95a2ec2d4d827efe6a922b
license    : Artistic-1.0-Perl
summary    : Perl HTTP date functions
component  : programming.perl
description: |
    This module provides functions that deal the date formats used by the HTTP protocol (and then some more). Only the first two functions, time2str() and str2time(), are exported by default.
patterns   :
    - /usr/share/man
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
