name       : perl-http-date
version    : 6.02
release    : 8
source     :
    - http://search.cpan.org/CPAN/authors/id/G/GA/GAAS/HTTP-Date-6.02.tar.gz : e8b9941da0f9f0c9c01068401a5e81341f0e3707d1c754f8e11f42a7e629e333
license    : Artistic-1.0-Perl
summary    : Perl HTTP date functions
component  : programming.perl
description: |
    This module provides functions that deal the date formats used by the HTTP protocol (and then some more). Only the first two functions, time2str() and str2time(), are exported by default.
patterns   :
    - /usr/share/man
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
